{% set version = "0.6.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-officer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/officer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/officer/officer_{{ version }}.tar.gz
  sha256: ebb270100cf943897f5f2fc900effbab886cce18c4e2b4c218a3f3dcee52f7d3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-openssl
    - r-r6
    - r-ragg
    - r-uuid
    - r-xml2 >=1.1.0
    - r-zip >=2.1.0
  run:
    - r-base
    - r-openssl
    - r-r6
    - r-ragg
    - r-uuid
    - r-xml2 >=1.1.0
    - r-zip >=2.1.0

test:
  commands:
    - $R -e "library('officer')"           # [not win]
    - "\"%R%\" -e \"library('officer')\""  # [win]

about:
  home: https://davidgohel.github.io/officer
  dev_url: https://github.com/davidgohel/officer/
  doc_url: https://davidgohel.github.io/officer/reference/index.html
  license: MIT
  summary: Access and manipulate 'Microsoft Word' and 'Microsoft PowerPoint' documents from R. The package focuses on tabular and graphical reporting from R; it also provides two functions that let users get document content into data objects. A set of functions lets add and remove images, tables and paragraphs of text in
    new or existing documents. The package does not require any installation of Microsoft products to be able to write Microsoft files.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
