# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IBsh7rskttzCi3ga3gkMSOEsyyL39/LIseMPmkE8shdtCzrNUrElxLE2NJ5IYGEfIMoIrPgnf7j5yM24/j6CtwKFftZW6UEDBi2hPdTkLKD91daa3sqarMe/xr/HMpYXpnSq0xjY306l3xWb8l8arUqsh9dSJTA2FUaRZIVo5ojFRe3ouuTuZXh7vO6WTl5mCn+ZIOwp7qOJJoSdrDPCfTF427Q/DHCkcAt1+aEn6pJLjrd5eb2M9xrlEpB3RuhD9VSYqxoNT9mmJwcHxiCWOWf2HGcnZoWvJoOb1RCZuZmEYCY4mS5foN3xD+psznoIgr94lBEMKh6ZfgVzbpLphOKUH0op9cRGa1+EGMnbJc5olv8+6eJ8eRhBy/n0Zn3X/uP2j8pVA7Q6ToWClKveq1hLud1KpTCmiTZ+qw8aUo8o+jh/XcWR8btLrQlnbHKLOeHqn6R7dtAUUOkMUD/CCG+RjGP3MUMqJYupfEDZxWqu3Ylm92E2rMgxxHbAQtWZ2ppx+ZhyCqq9IIAn4XFtOI+LxOUdYsCxo/WMdluJ2OXum5jKbJPOIDOg8ngwYk2G8IwVW+9xhVsaZOKU/4kQ1Mhv3Lk079rCNAU11HdzLZQJElMIsowPfJxNaSA6rZc9U8HnARuEyULkL5mVIkEzN5Lg7uNrRSmFiH9k22BOQUc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
