appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IBsh7rskttzCi3ga3gkMSOEsyyL39/LIseMPmkE8shdtCzrNUrElxLE2NJ5IYGEfIMoIrPgnf7j5yM24/j6CtwKFftZW6UEDBi2hPdTkLKD91daa3sqarMe/xr/HMpYXpnSq0xjY306l3xWb8l8arUqsh9dSJTA2FUaRZIVo5ojFRe3ouuTuZXh7vO6WTl5mCn+ZIOwp7qOJJoSdrDPCfTF427Q/DHCkcAt1+aEn6pJLjrd5eb2M9xrlEpB3RuhD9VSYqxoNT9mmJwcHxiCWOWf2HGcnZoWvJoOb1RCZuZmEYCY4mS5foN3xD+psznoIgr94lBEMKh6ZfgVzbpLphOKUH0op9cRGa1+EGMnbJc5olv8+6eJ8eRhBy/n0Zn3X/uP2j8pVA7Q6ToWClKveq1hLud1KpTCmiTZ+qw8aUo8o+jh/XcWR8btLrQlnbHKLOeHqn6R7dtAUUOkMUD/CCG+RjGP3MUMqJYupfEDZxWqu3Ylm92E2rMgxxHbAQtWZ2ppx+ZhyCqq9IIAn4XFtOI+LxOUdYsCxo/WMdluJ2OXum5jKbJPOIDOg8ngwYk2G8IwVW+9xhVsaZOKU/4kQ1Mhv3Lk079rCNAU11HdzLZQJElMIsowPfJxNaSA6rZc9U8HnARuEyULkL5mVIkEzN5Lg7uNrRSmFiH9k22BOQUc=
conda_forge_output_validation: true
